delete CRDs, refer to dev portal controller as source of truth
Signed-off-by: Jason Madigan <jason@jasonmadigan.com>

diff --git a/kuadrant-dev-setup/Makefile b/kuadrant-dev-setup/Makefile
--- a/kuadrant-dev-setup/Makefile
+++ b/kuadrant-dev-setup/Makefile
@@ -1,9 +1,10 @@
-.PHONY: help kind-create kind-delete kuadrant-install demo-install demo-uninstall clean
+.PHONY: help kind-create kind-delete kuadrant-install controller-deploy demo-install demo-uninstall clean
 
 CLUSTER_NAME ?= local-cluster
 LOCALBIN ?= $(shell pwd)/bin
 KIND_VERSION ?= v0.20.0
 HELM_VERSION ?= v3.15.0
+CONTROLLER_REPO ?= ../../developer-portal-controller
 
 help:
 	@echo "kuadrant development setup for rhdh"
@@ -13,11 +14,12 @@ help:
 	@echo "  cd .. && yarn dev   - start rhdh with hot reload"
 	@echo ""
 	@echo "cluster management:"
-	@echo "  make kind-create    - create kind cluster + install kuadrant + demo"
+	@echo "  make kind-create    - create kind cluster + install kuadrant + controller + demo"
 	@echo "  make kind-delete    - delete kind cluster"
 	@echo ""
 	@echo "kuadrant:"
 	@echo "  make kuadrant-install   - install kuadrant v1.3.0"
+	@echo "  make controller-deploy  - deploy developer-portal-controller"
 	@echo "  make demo-install       - install toystore demo"
 	@echo "  make demo-uninstall     - remove toystore demo"
 	@echo ""
@@ -92,10 +94,13 @@ kind-create: $(LOCALBIN)/kind-$(KIND_VERSION) $(LOCALBIN)/helm-$(HELM_VERSION)
 	@echo "installing kuadrant..."
 	@$(MAKE) kuadrant-install
 	@echo ""
+	@echo "deploying developer-portal-controller..."
+	@$(MAKE) controller-deploy
+	@echo ""
 	@echo "installing demo resources..."
 	@$(MAKE) demo-install
 	@echo ""
-	@echo "cluster ready! kuadrant and demo resources installed."
+	@echo "cluster ready! kuadrant, controller and demo resources installed."
 	@echo ""
 	@echo "next: cd .. && yarn dev"
 
@@ -126,17 +131,27 @@ kuadrant-install: $(LOCALBIN)/helm-$(HELM_VERSION)
 	@echo "creating kuadrant instance..."
 	@kubectl apply -f kuadrant-instance.yaml
 	@echo ""
-	@echo "installing custom crds..."
-	@kubectl apply -f crds/
-	@echo ""
 	@echo "kuadrant v1.3.0 installed!"
+
+controller-deploy:
+	@if [ ! -d "$(CONTROLLER_REPO)" ]; then \
+		echo "error: developer-portal-controller not found at $(CONTROLLER_REPO)"; \
+		echo ""; \
+		echo "please clone the controller repo:"; \
+		echo "  cd ../.. && git clone git@github.com:Kuadrant/developer-portal-controller.git"; \
+		echo ""; \
+		echo "or set CONTROLLER_REPO to point to your checkout:"; \
+		echo "  make kind-create CONTROLLER_REPO=/path/to/developer-portal-controller"; \
+		exit 1; \
+	fi
+	@echo "deploying developer-portal-controller from $(CONTROLLER_REPO)..."
+	@$(MAKE) -C $(CONTROLLER_REPO) local-deploy KIND_CLUSTER_NAME=$(CLUSTER_NAME)
+	@echo "developer-portal-controller deployed!"
 
 demo-install:
 	@echo "installing toystore demo resources..."
 	@kubectl apply -f demo/toystore-demo.yaml
 	@kubectl apply -f demo/additional-demos.yaml
-	# temp solution until developer-portal-controller does this
-	@kubectl patch apiproduct toystore-api -n toystore --subresource status --type=merge --patch "$$(cat demo/toystore-status.yaml)"
 	@echo ""
 	@echo "demo resources installed!"
 	@echo ""
